repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.1
  hooks:
  - id: ruff
    args:
    - --fix
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.4.0
  hooks:
  - id: black
    language_version: python3.11
